org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

mod.id=oniononion
mod.name=Onion Onion
mod.group=com.davigj
mod.version=3.1.0

deps.fabric-loader=0.19.2

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=
publish.curseforge=
#publish.additionalVersions=