modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/davidjjung/oniononion/issues"
license = "MIT License"

[[mods]]
modId = "onion_onion"
version = "${file.jarVersion}"
logoFile = "logo.png"
itemIcon = "farmersdelight:onion"
configBackground = "minecraft:textures/block/dirt.png"
authors = "DavigJ"
credits = "Vectorwing made a cool mod, Evo made cool sprites, and Uraneptus made a cool 1.20 port"
displayURL = "https://modrinth.com/mod/onion-onion"
displayName = "Onion Onion"
description = '''Giving onions some (ill-deserved?) love'''

[[dependencies.onion_onion]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.onion_onion]]
modId = "forge"
mandatory = true
versionRange = "[47.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.onion_onion]]
modId = "blueprint"
mandatory = true
versionRange = "[7.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.onion_onion]]
modId = "farmersdelight"
mandatory = true
versionRange = "[1.2.3,)"
ordering = "AFTER"
side = "BOTH"